#!/usr/bin/env node
/**
 * Bundle the edge entrypoint (`dist/edge.js` → resolveBook + interpolate) into a
 * single self-contained ESM file with no external imports, consumable by Deno /
 * edge runtimes that cannot apply an import map. Run after the tsgo build.
 */
import { build } from "esbuild";

await build({
  entryPoints: ["dist/edge.js"],
  bundle: true,
  format: "esm",
  platform: "neutral",
  treeShaking: true,
  outfile: "dist/edge/index.js",
  banner: { js: "// Generated by `npm run build:edge`; do not edit by hand." },
});

console.log("wrote dist/edge/index.js");
